fix(deps): update roborazzi to v1.58.0 (#738)
This PR contains the following updates:

| Package | Change |
[Age](https://docs.renovatebot.com/merge-confidence/) |
[Confidence](https://docs.renovatebot.com/merge-confidence/) |
|---|---|---|---|
|
[io.github.takahirom.roborazzi](https://redirect.github.com/takahirom/roborazzi)
| `1.56.0` → `1.58.0` |
![age](https://developer.mend.io/api/mc/badges/age/maven/io.github.takahirom.roborazzi:io.github.takahirom.roborazzi.gradle.plugin/1.58.0?slim=true)
|
![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.github.takahirom.roborazzi:io.github.takahirom.roborazzi.gradle.plugin/1.56.0/1.58.0?slim=true)
|
|
[io.github.takahirom.roborazzi:roborazzi-junit-rule](https://redirect.github.com/takahirom/roborazzi)
| `1.56.0` → `1.58.0` |
![age](https://developer.mend.io/api/mc/badges/age/maven/io.github.takahirom.roborazzi:roborazzi-junit-rule/1.58.0?slim=true)
|
![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.github.takahirom.roborazzi:roborazzi-junit-rule/1.56.0/1.58.0?slim=true)
|
|
[io.github.takahirom.roborazzi:roborazzi-compose](https://redirect.github.com/takahirom/roborazzi)
| `1.56.0` → `1.58.0` |
![age](https://developer.mend.io/api/mc/badges/age/maven/io.github.takahirom.roborazzi:roborazzi-compose/1.58.0?slim=true)
|
![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.github.takahirom.roborazzi:roborazzi-compose/1.56.0/1.58.0?slim=true)
|
|
[io.github.takahirom.roborazzi:roborazzi](https://redirect.github.com/takahirom/roborazzi)
| `1.56.0` → `1.58.0` |
![age](https://developer.mend.io/api/mc/badges/age/maven/io.github.takahirom.roborazzi:roborazzi/1.58.0?slim=true)
|
![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.github.takahirom.roborazzi:roborazzi/1.56.0/1.58.0?slim=true)
|

---

### Release Notes

<details>
<summary>takahirom/roborazzi (io.github.takahirom.roborazzi)</summary>

###
[`v1.58.0`](https://redirect.github.com/takahirom/roborazzi/releases/tag/1.58.0)

[Compare
Source](https://redirect.github.com/takahirom/roborazzi/compare/1.57.0...1.58.0)

##### Bugfix: Fixed NoClassDefFoundError in RoborazziPlugin when the
Android Plugin is not applied

Previously, we never touched the Android Plugin class when it wasn’t in
use; nevertheless, a NoClassDefFoundError was raised because the plugin
contained a method that referenced the Android Plugin class. I therefore
extracted Android-related code into a separate class to resolve the
issue. Thank you, [@&#8203;rnett](https://redirect.github.com/rnett),
for reporting this.

##### Update: Device qualifiers

You can now specify device qualifiers via RobolectricDeviceQualifiers.
The list has been expanded with new devices such as Pixel9, XRGlasses,
and even AIGlasses!
Thank you, [@&#8203;joergmis](https://redirect.github.com/joergmis), for
your contribution.

##### What's Changed

- Ensure StoreScreenshot records Android host tests by
[@&#8203;takahirom](https://redirect.github.com/takahirom) in
[#&#8203;790](https://redirect.github.com/takahirom/roborazzi/pull/790)
- Use debug unit test for roborazzi-core by
[@&#8203;takahirom](https://redirect.github.com/takahirom) in
[#&#8203;792](https://redirect.github.com/takahirom/roborazzi/pull/792)
- Update device qualifiers by
[@&#8203;joergmis](https://redirect.github.com/joergmis) in
[#&#8203;793](https://redirect.github.com/takahirom/roborazzi/pull/793)
- Isolate Android-specific code to support non-Android KMP projects by
[@&#8203;takahirom](https://redirect.github.com/takahirom) in
[#&#8203;795](https://redirect.github.com/takahirom/roborazzi/pull/795)

##### New Contributors

- [@&#8203;joergmis](https://redirect.github.com/joergmis) made their
first contribution in
[#&#8203;793](https://redirect.github.com/takahirom/roborazzi/pull/793)

**Full Changelog**:
<https://github.com/takahirom/roborazzi/compare/1.57.0...1.58.0>

###
[`v1.57.0`](https://redirect.github.com/takahirom/roborazzi/releases/tag/1.57.0)

[Compare
Source](https://redirect.github.com/takahirom/roborazzi/compare/1.56.0...1.57.0)

##### Fix AGP 9.0 KMP preview screenshots

We had been using
`unitTestSources?.**java**?.addGeneratedSourceDirectory`, but this
approach proved ineffective when we adopted
`com.android.kotlin.multiplatform.library`. Consequently, we migrated to
`unitTestSources?.**kotlin**?.addGeneratedSourceDirectory` for the KMP
plugin. Unfortunately, when applying `com.android.library`,
`unitTestSources?.kotlin` remains non-functional, so we must toggle
between the two depending on the plugin.
Thank you for reporting this
[@&#8203;HLCaptain](https://redirect.github.com/HLCaptain) !

(This is our plugin code, you don't have to write this.)

```kotlin
  val isKmpLibrary = project.plugins.hasPlugin("com.android.kotlin.multiplatform.library")
  if (isKmpLibrary) {
    unitTestSources?.kotlin?.addGeneratedSourceDirectory(
      generateTestsTask,
      GenerateComposePreviewRobolectricTestsTask::outputDir
    )
  } else {
    unitTestSources?.java?.addGeneratedSourceDirectory(
      generateTestsTask,
      GenerateComposePreviewRobolectricTestsTask::outputDir
    )
  }
```

##### Bugfix: Compose Preview’s `onSizeChanged{}` wasn’t called when
multiple windows exist.

There is a bug in which Compose Preview’s `onSizeChanged{}` fails to
fire when multiple windows are present. This issue arises because we
neglected to invoke

```kotlin
      composeTestRule.mainClock.advanceTimeByFrame()
      composeTestRule.waitForIdle()
```

Reproducing screenshots <img width="924" height="646" alt="image"
src="https://github.com/user-attachments/assets/331853f5-0b8a-45f6-b230-7baf2ac524a3"
/>

##### What's Changed

- \[CI] Migrate from gradle-build-action to gradle/actions/setup-gradle
by [@&#8203;takahirom](https://redirect.github.com/takahirom) in
[#&#8203;788](https://redirect.github.com/takahirom/roborazzi/pull/788)
- Add PreviewPopupWithMeasure for reproduction by
[@&#8203;takahirom](https://redirect.github.com/takahirom) in
[#&#8203;787](https://redirect.github.com/takahirom/roborazzi/pull/787)
- Fix doBeforeCapture not called with multiple windows by
[@&#8203;takahirom](https://redirect.github.com/takahirom) in
[#&#8203;786](https://redirect.github.com/takahirom/roborazzi/pull/786)
- Use sources.kotlin for KMP library generated test sources by
[@&#8203;takahirom](https://redirect.github.com/takahirom) in
[#&#8203;789](https://redirect.github.com/takahirom/roborazzi/pull/789)

**Full Changelog**:
<https://github.com/takahirom/roborazzi/compare/1.56.0...1.57.0>

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/EmergeTools/hackernews).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0Mi45Ny4wIiwidXBkYXRlZEluVmVyIjoiNDIuOTcuMCIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOltdfQ==-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>